Repository Geoxor/Amethyst, pull requests merged in 2022-10, with the labels that each got.

#51 An electron-based audio player with a funny looking bloat
  README.md
Labels: docs

#103 fixed startup song stuff
  src/renderer/components/PlaybackButtons.vue
  src/renderer/player.ts
Labels: enhancement, bug-fix

#104 added a bug that adds a feature to fix a bug
  src/renderer/App.vue
  src/renderer/components/nodes/MasterNode.vue
  src/renderer/components/visualizers/SpectrumAnalyzer.vue
  src/renderer/components/visualizers/VectorscopeAnalyzer.vue
  src/renderer/icons/material/MasterIcon.vue
  src/renderer/logic/audio.ts
Labels: bug, enhancement, bug-fix

#105 fix #89
  src/renderer/components/PlaybackButtons.vue
Labels: bug-fix

#106 set volume on master node instead of input node
  src/renderer/logic/audio.ts
  src/renderer/player.ts
Labels: enhancement

#107 added reset context menu option to nodes
  src/renderer/components/nodes/CustomNode.vue
  src/renderer/logic/audio.ts
Labels: enhancement
