Repository Geoxor/Amethyst, pull requests merged in 2025-05, with the labels that each got.

#774 Feat/Inspectable nodes
  src/renderer/components/BaseChip.vue
  src/renderer/components/Inspector/InspectorBar.vue
  src/renderer/components/Inspector/index.ts
  src/renderer/components/NavigationBar.vue
  src/renderer/components/input/DraggableModifierInput.vue
  src/renderer/components/nodes/CustomNode.vue
  src/renderer/components/nodes/QuickMenu.vue
  src/renderer/components/settings/SettingsGroup.vue
  src/renderer/components/visualizers/DbMeter.vue
  src/renderer/locales/en-US.json
  src/renderer/logic/audio.ts
  src/renderer/logic/audioManager.ts
  src/renderer/nodes/EightBandEqualizerNode/component.vue
  src/renderer/nodes/EightBandEqualizerNode/index.ts
  src/renderer/nodes/FilterNode/component.vue
  src/renderer/nodes/FilterNode/index.ts
  src/renderer/nodes/GainNode/component.vue
  src/renderer/nodes/GainNode/index.ts
  src/renderer/nodes/InputNode/component.vue
  src/renderer/nodes/InputNode/index.ts
  src/renderer/nodes/MasterNode/component.vue
  src/renderer/nodes/MasterNode/index.ts
  src/renderer/nodes/OutputNode/component.vue
  src/renderer/nodes/OutputNode/index.ts
  src/renderer/nodes/PannerNode/PannerGraphics.vue
  src/renderer/nodes/PannerNode/component.vue
  src/renderer/nodes/PannerNode/index.ts
  src/renderer/nodes/SpectrumNode/component.vue
  src/renderer/nodes/SpectrumNode/index.ts
  src/renderer/nodes/index.ts
  src/renderer/views/NodeEditorView.vue
  src/renderer/views/Settings/AppearanceSettings.vue
Labels: enhancement, bug-fix

#776 docs: Improve information readability
  docs/development.mdx
Labels: docs

#777 fix: make it packagable on aarch64 linux
  package.json
  src/main/discord.ts
Labels: bug-fix

#778 Feat/realtime audio
  package.json
  src/main/main.ts
  src/main/mainWindow.ts
  src/main/realtimeAudio.ts
  src/renderer/amethyst.ts
  src/renderer/components/v2/DropdownInput.vue
  src/renderer/components/v2/OutputBreakdown.vue
  src/renderer/components/v2/OutputDiagram.vue
  src/renderer/components/v2/OutputDiagramBlob.vue
  src/renderer/icons/logos/AsioLogo.vue
  src/renderer/icons/logos/FLStudioLogo.vue
  src/renderer/locales/en-US.json
  src/renderer/locales/ja-JP.json
  src/renderer/logic/audioManager.ts
  src/renderer/logic/math.ts
  src/renderer/logic/player.ts
  src/renderer/nodes/InputNode/component.vue
  src/renderer/nodes/MasterNode/component.vue
  src/renderer/nodes/OutputNode/component.vue
  src/renderer/nodes/OutputNode/index.ts
  src/renderer/state.ts
  src/renderer/views/Settings/AudioSettings.vue
  src/renderer/workers/processor.js
  yarn.lock
Labels: enhancement, help-wanted

#783 rpc: change rpc display information to be cleaner
  src/main/discord.ts
  src/main/mainWindow.ts
  src/renderer/amethyst.ts
  src/renderer/logic/track.ts
Labels: enhancement

#773 Feature/Shader Effects
  src/renderer/App.vue
  src/renderer/amethyst.ts
  src/renderer/components/BackgroundImage.vue
  src/renderer/components/ShaderCanvas.vue
  src/renderer/components/v2/PlaybackControls.vue
  src/renderer/components/visualizers/SpectrumAnalyzer.vue
  src/renderer/components/visualizers/SpectrumAnalyzer/SpectrumAnalyzer.vue
  src/renderer/components/visualizers/SpectrumAnalyzer/SpectrumFrag.glsl
  src/renderer/components/visualizers/SpectrumAnalyzer/SpectrumVertex.glsl
  src/renderer/components/visualizers/SpectrumAnalyzer/index.ts
  src/renderer/locales/en-US.json
  src/renderer/logic/color.ts
  src/renderer/logic/math.ts
  src/renderer/nodes/EightBandEqualizerNode/component.vue
  src/renderer/nodes/SpectrumNode/component.vue
  src/renderer/shaders/ShaderManager.ts
  src/renderer/shaders/builtin/SimpleGradient.ts
  src/renderer/shaders/components/SpectrogramShader.ts
  src/renderer/shaders/components/SpectrumShader.ts
  src/renderer/state.ts
  src/renderer/views/Settings/AppearanceSettings.vue
  src/renderer/views/Settings/MeteringSettings.vue
  src/shared/constants.ts
Labels: enhancement

#784 chore: correct nvm installation version instructions
  docs/development.mdx
Labels: docs

#785 Feat/native drag drop
  assets/images/audio64x64.png
  src/main/drag-drop.ts
  src/main/main.ts
  src/main/preload.ts
  src/renderer/components/LazyList.vue
  src/renderer/types/window.d.ts
Labels: enhancement

#787 Improvements to Playback Controls
  src/renderer/components/v2/PlaybackControls.vue
  src/renderer/components/visualizers/LoudnessMeter.vue
  src/renderer/components/visualizers/OscilloscopeAnalyzer.vue
  src/renderer/components/visualizers/SpectrumAnalyzer.vue
  src/renderer/components/visualizers/VectorscopeAnalyzer.vue
  src/renderer/locales/de-DE.json
  src/renderer/locales/el-GR.json
  src/renderer/locales/en-GB.json
  src/renderer/locales/en-US.json
  src/renderer/locales/fi-FI.json
  src/renderer/locales/fr-FR.json
  src/renderer/locales/ja-JP.json
  src/renderer/locales/pl-PL.json
  src/renderer/locales/pt-BR.json
  src/renderer/locales/ru-RU.json
  src/renderer/state.ts
  src/renderer/views/Settings/MeteringSettings.vue
Labels: enhancement

#792 Feat/discovery page
  src/main/metadata.ts
  src/main/preload.ts
  src/main/utility.js
  src/main/utility.ts
  src/renderer/amethyst.ts
  src/renderer/components/DiscoveryFeed.vue
  src/renderer/components/Inspector/InspectorBar.vue
  src/renderer/components/LazyList.vue
  src/renderer/components/NavigationBar.vue
  src/renderer/components/TrackCard.vue
  src/renderer/components/settings/SettingsCategory.vue
  src/renderer/components/visualizers/DbMeter.vue
  src/renderer/locales/en-US.json
  src/renderer/logic/analytics.ts
  src/renderer/logic/player.ts
  src/renderer/logic/queue.ts
  src/renderer/logic/settings.ts
  src/renderer/logic/track.ts
  src/renderer/router.ts
  src/renderer/state.ts
  src/renderer/types/window.d.ts
  src/renderer/views/DiscoveryView.vue
Labels: enhancement

#795 Chore/locale coverage
  .github/workflows/ci.yml
  .github/workflows/update-localization.yml
  LOCALE_COVERAGE.md
  README.md
  scripts/injectCoverage.ts
  scripts/localizationStatus.ts
  src/renderer/locales/el-GR.json
Labels: docs

#799 New option for the icon color in the settings
  assets/colorless_icon.png
  assets/colorless_icon.svg
  src/main/mainWindow.ts
  src/renderer/App.vue
  src/renderer/locales/en-US.json
  src/renderer/locales/ru-RU.json
  src/renderer/logic/settings.ts
  src/renderer/state.ts
  src/renderer/views/Settings/AppearanceSettings.vue
Labels: enhancement

#796 convert project to ESM in preparation to replace WindiCSS
  .eslintrc
  .vscode/settings.json
  electromon.json
  eslint.config.ts
  package.json
  src/android/app/capacitor.build.gradle
  src/android/capacitor.settings.gradle
  src/main/discord.ts
  src/main/drag-drop.ts
  src/main/main.ts
  src/main/mainWindow.ts
  src/main/metadata.ts
  src/main/preload.ts
  src/main/realtimeAudio.ts
  src/main/tsconfig.json
  src/main/utility.js
  src/main/utility.ts
  src/renderer/amethyst.ts
  src/renderer/components/ContextMenu/index.ts
  src/renderer/components/Inspector/InspectorBar.vue
  src/renderer/components/input/BaseKeyboardButton.vue
  src/renderer/components/v2/PlaybackControls.vue
  src/renderer/components/v2/ResizableSettingsNavigation.vue
  src/renderer/components/visualizers/OscilloscopeAnalyzer.vue
  src/renderer/components/visualizers/SpectrumAnalyzer.vue
  src/renderer/electronEventManager.ts
  src/renderer/logic/analytics.ts
  src/renderer/logic/audio.ts
  src/renderer/logic/audioManager.ts
  src/renderer/logic/color.test.ts
  src/renderer/logic/math.test.ts
  src/renderer/logic/mediaSession.ts
  src/renderer/logic/mediaSources.ts
  src/renderer/logic/player.ts
  src/renderer/logic/queue.ts
  src/renderer/logic/settings.ts
  src/renderer/logic/track.ts
  src/renderer/nodes/index.ts
  src/renderer/shaders/components/SpectrogramShader.ts
  src/renderer/shaders/components/SpectrumShader.ts
  src/renderer/state.ts
  src/renderer/types/window.d.ts
  src/renderer/views/NodeEditorView.vue
  src/renderer/views/Settings/AppearanceSettings.vue
  src/renderer/views/Settings/MeteringSettings.vue
  tsconfig.json
  yarn.lock
Labels: dependencies

#810 feat: macOS native menubar items
  src/main/main.ts
  src/main/mainWindow.ts
  src/renderer/amethyst.ts
  src/renderer/components/TopBar.vue
Labels: enhancement

#809 New Crowdin updates
  src/renderer/locales/cs-CZ.json
  src/renderer/locales/es-ES.json
Labels: docs

#835 Implement "Local Sources" for Android (#833)
  src/android/app/src/main/AndroidManifest.xml
  src/android/app/src/main/java/com/example/app/MainActivity.java
  src/renderer/amethyst.ts
  src/renderer/logic/mediaSources.ts
Labels: bug, enhancement

#837 Improve Android development documentation
  docs/guides/android.mdx
  example.env
Labels: docs

#839 iOS mobile bringup
  capacitor.config.ts
  src/ios/App/App.xcodeproj/project.pbxproj
  src/ios/App/App/App.entitlements
  src/ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png
  src/ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/ios/App/App/Assets.xcassets/AppIcon.appiconset/logo.png
  src/ios/App/App/Assets.xcassets/Contents.json
  src/ios/App/App/Assets.xcassets/Splash.imageset/Contents.json
  src/ios/App/App/Assets.xcassets/Splash.imageset/splash 1.png
  src/ios/App/App/Assets.xcassets/Splash.imageset/splash 2.png
  src/ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732-1.png
  src/ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732-2.png
  src/ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732.png
  src/ios/App/App/Assets.xcassets/Splash.imageset/splash.png
  src/ios/App/App/Info.plist
  src/renderer/amethyst.ts
  src/renderer/index.html
  src/renderer/state.ts
Labels: bug, enhancement

#840 Add Linux JDK Installation Instructions
  docs/guides/android.mdx
Labels: docs

#841 Fix memory a few leaks
  src/renderer/components/nodes/CustomNode.vue
  src/renderer/logic/queue.ts
  src/renderer/views/NodeEditorView.vue
Labels: bug

#843 Add scrobbling support from feat/last.fm
  docs/guides/player_events.mdx
  src/renderer/amethyst.ts
  src/renderer/components/BaseInput.vue
  src/renderer/components/settings/SettingsSetting.vue
  src/renderer/components/v2/TitleSubtitle.vue
  src/renderer/locales/en-US.json
  src/renderer/logic/lastFM.ts
  src/renderer/logic/player.ts
  src/renderer/logic/settings.ts
  src/renderer/views/Settings/IntegrationSettings.vue
Labels: bug, enhancement, docs
