Repository Geoxor/Amethyst, pull requests merged in 2025-04, with the labels that each got.

#739 fix: dragging unallowed files causing queue to play last song
  src/renderer/amethyst.ts
Labels: bug-fix

#745 feat: resizing of playback controls
  src/renderer/components/ResizableDiv/ResizeHandle.vue
  src/renderer/components/ResizableDiv/component.vue
  src/renderer/components/ResizableDiv/index.ts
  src/renderer/components/v2/PlaybackControls.vue
  src/renderer/components/v2/ResizableSettingsNavigation.vue
Labels: enhancement

#749 improve translations to the pt-BR locale
  src/renderer/locales/pt-BR.json
Labels: enhancement

#758 Fix issues with importing a folder
  src/renderer/amethyst.ts
Labels: bug-fix

#769 Add disk number to trackNumber comparator
  src/renderer/logic/queue.ts
Labels: bug, enhancement, bug-fix

#771 feat: detect audio drivers
  package.json
  src/main/main.ts
  src/renderer/amethyst.ts
  src/renderer/components/LazyList.vue
  src/renderer/components/v2/OutputBreakdown.vue
  src/renderer/components/v2/OutputDiagram.vue
  src/renderer/components/v2/OutputDiagramBlob.vue
  src/renderer/icons/logos/ArturiaLogo.vue
  src/renderer/icons/logos/FocusriteLogo.vue
  src/renderer/icons/logos/NvidiaLogo.vue
  src/renderer/icons/logos/RealtekLogo.vue
  src/renderer/icons/logos/SoundIDLogo.vue
  src/renderer/icons/logos/SteamLogo.vue
  src/renderer/locales/en-US.json
  src/renderer/logic/player.ts
  src/renderer/state.ts
  src/renderer/views/Settings/AudioSettings.vue
  yarn.lock
Labels: enhancement, help-wanted, bug-fix
